apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: app1
  name: monitor-app1
  namespace: aluno-phillipe
spec:
  podMetricsEndpoints:
  - port: "5000"
    interval: 10s
  selector:
    matchLabels:
      app: app1
